[package]
name = "testbot"
version = "0.1.0"
authors = ["Travis Carr <tmcarr89@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.17.4"
r2d2_postgres = "0.16.0"
rand = "0.7"
serenity = "0.8"
env_logger = "0.6"
kankyo = "0.2"
log = "0.4"
pickledb = "0.4.1"
serde = { version = "1.0.82", features = ["derive"] }
