name: Daily Bloat Check

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 12 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Run cargo bloat
        uses: orf/cargo-bloat-action@v1
